In [3]:
##Statistics

In [4]:
import numpy as np

In [5]:
stats = np.array([[1,2,3],[4,5,6]])

In [6]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.min(stats)

1

In [8]:
np.max(stats)

6

In [9]:
np.max(stats,axis=1)

array([3, 6])

In [10]:
np.min(stats,axis=1)

array([1, 4])

In [11]:
np.sum(stats,axis=1)

array([ 6, 15])

In [12]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [13]:
##reorganizing arrays

In [20]:
a=np.array([[1,2,3,4],[5,6,7,8]])

In [21]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
beam = np.array([[1,2,3,4],[5,6,7,8]])
beam

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
ally = before.reshape((2,2,2))

In [39]:
ally

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
a = np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [31]:
b = a.reshape((8,1))

In [32]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [35]:
b = a.reshape((4,2))

In [36]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
## vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])   ##stacking arrays in sequence vertically(row wise)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [42]:
##horizontal stacking vector
h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])
h3 = np.array([9,8,7,5])
np.hstack([h1,h2,h3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 8, 7, 5])

In [43]:
np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8])