In [1]:
##Mathematics_operators

In [3]:
import numpy as np

In [4]:
a = np.array([2,7,5,4])

In [5]:
a

array([2, 7, 5, 4])

In [6]:
a+2

array([4, 9, 7, 6])

In [7]:
a-2

array([0, 5, 3, 2])

In [8]:
a*2

array([ 4, 14, 10,  8])

In [9]:
a/2

array([1. , 3.5, 2.5, 2. ])

In [10]:
a+=2

In [11]:
a

array([4, 9, 7, 6])

In [12]:
b = np.array([5,5,5,5])

In [13]:
b

array([5, 5, 5, 5])

In [14]:
a+b  ## [5+4,5+9,5+7,5+6]

array([ 9, 14, 12, 11])

In [15]:
a**2

array([16, 81, 49, 36], dtype=int32)

In [16]:
##sin
np.sin(a)

array([-0.7568025 ,  0.41211849,  0.6569866 , -0.2794155 ])

In [17]:
##cos
np.cos(a)

array([-0.65364362, -0.91113026,  0.75390225,  0.96017029])

In [18]:
np.tan(a)

array([ 1.15782128, -0.45231566,  0.87144798, -0.29100619])

In [20]:
a = np.ones(a)

In [21]:
a

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        ...,

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         ...,
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1.

In [22]:
u  = np.ones((2,3))

In [23]:
u

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
t = np.full((3,2),2)

In [25]:
t

array([[2, 2],
       [2, 2],
       [2, 2]])

In [26]:
##matrix multiplication
np.matmul(u,t) ##this function returns the matrix in 2 array,if we do u*t= we get error.

array([[6., 6.],
       [6., 6.]])

In [27]:
##finding determinant
x = np.identity(3)  ##linear algebra determinant
np.linalg.det(x)    ##This function determines the input matrix

1.0

In [31]:
y =np.identity(11)
np.linalg.det(y)

1.0