In [1]:
Exercise


import sys
import numpy as np

Numpy Arrays

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1,2,3,4])

In [4]:
a

array([1, 2, 3, 4])

In [5]:
a[0],a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[::2]

array([1, 3])

In [10]:
b = np.array([0, .5, 1, 1.5, 2])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0],b[1],b[2]

(0.0, 0.5, 1.0)

In [13]:
b[[0,2,-1]]

array([0., 1., 2.])

##Array type

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int32')

In [16]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1,2,3,4],dtype=np.float)

C:\Users\User\AppData\Local\Temp/ipykernel_4728/2214947681.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4],dtype=np.float)


array([1., 2., 3., 4.])

In [19]:
np.array([1,2,3,4],dtype=np.float64)

array([1., 2., 3., 4.])

In [20]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [21]:
d = np.array([{'a': 1}, sys])

In [22]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [24]:
c = np.array(['a','b','c'])

In [25]:
c

array(['a', 'b', 'c'], dtype='<U1')

In [26]:
c.dtype

dtype('<U1')

In [27]:
d.dtype

dtype('O')

In [28]:
A = np.array([[1,2,3],[2,3,4]])

In [29]:
A

array([[1, 2, 3],
       [2, 3, 4]])

In [30]:
A.shape

(2, 3)

In [31]:
B = np.array([[1,2],[2,3],[3,4]])

In [32]:
B

array([[1, 2],
       [2, 3],
       [3, 4]])

In [33]:
B.shape

(3, 2)

In [34]:
A.ndim

2

In [35]:
B.ndim

2

In [36]:
A.size

6

In [37]:
B.size

6

In [38]:
C = np.array([[5,6,7],[4,3,1],[8,9,10]])

In [39]:
C

array([[ 5,  6,  7],
       [ 4,  3,  1],
       [ 8,  9, 10]])

In [40]:
C.shape

(3, 3)

In [41]:
C.ndim

2

In [42]:
C.size

9

In [43]:
D = np.array([[[6,7,8],[11,34,56]],[[2,8,9],[10,5,20]]])

In [44]:
D

array([[[ 6,  7,  8],
        [11, 34, 56]],

       [[ 2,  8,  9],
        [10,  5, 20]]])

In [45]:
D.ndim

3

In [46]:
D.size

12

In [47]:
D.shape

(2, 2, 3)

In [48]:
E =np.array([[[9,6,3],[10,11,12],[15,5,9]],[[32,56,78],[3,78,45],[4,7,5]],[[90,7,50],[1,9,0],[5,5,5]]])

In [49]:
E

array([[[ 9,  6,  3],
        [10, 11, 12],
        [15,  5,  9]],

       [[32, 56, 78],
        [ 3, 78, 45],
        [ 4,  7,  5]],

       [[90,  7, 50],
        [ 1,  9,  0],
        [ 5,  5,  5]]])

In [50]:
E.shape

(3, 3, 3)

In [51]:
E.ndim

3

In [52]:
E.size

27

In [60]:
F = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]],dtype= np.int64)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

##indexing and slicing of matrices

In [62]:
               #0 #1 #2
A = np.array([[40,50,60],  #0
              [34,43,53],  #1
              [67,56,34]]) #2

In [63]:
A

array([[40, 50, 60],
       [34, 43, 53],
       [67, 56, 34]])

In [64]:
A.ndim

2

In [66]:
A.size

9

In [67]:
A.shape

(3, 3)

In [68]:
A[0]

array([40, 50, 60])

In [69]:
A[1]

array([34, 43, 53])

In [70]:
A[2]

array([67, 56, 34])

In [71]:
A[1,2]  #[from first row,show 2nd element]

53

In [72]:
A[2,0]

67

In [73]:
A[0:2]

array([[40, 50, 60],
       [34, 43, 53]])

In [74]:
A[1:2]

array([[34, 43, 53]])

In [75]:
A[:2]

array([[40, 50, 60],
       [34, 43, 53]])

In [76]:
A[2:2]

array([], shape=(0, 3), dtype=int32)

In [77]:
A[:,:2]

array([[40, 50],
       [34, 43],
       [67, 56]])

In [78]:
A[2:,:]

array([[67, 56, 34]])

In [79]:
A[2:,2:]

array([[34]])

In [81]:
A[2:,:2]

array([[67, 56]])

In [82]:
A[0:,0:]

array([[40, 50, 60],
       [34, 43, 53],
       [67, 56, 34]])

In [83]:
A[1:,1:]

array([[43, 53],
       [56, 34]])

In [84]:
A[2:,:2]

array([[67, 56]])

In [85]:
A[:3]

array([[40, 50, 60],
       [34, 43, 53],
       [67, 56, 34]])

In [86]:
A[:2]

array([[40, 50, 60],
       [34, 43, 53]])

In [87]:
A[:1]

array([[40, 50, 60]])

In [88]:
A[:0]

array([], shape=(0, 3), dtype=int32)

In [89]:
A[:2,:1]

array([[40],
       [34]])

In [90]:
A[:2,0:]

array([[40, 50, 60],
       [34, 43, 53]])

In [91]:
A[:2,2:]

array([[60],
       [53]])

In [92]:
A

array([[40, 50, 60],
       [34, 43, 53],
       [67, 56, 34]])

In [93]:
A[2]=70 #2nd row is replaced with 70

In [94]:
A

array([[40, 50, 60],
       [34, 43, 53],
       [70, 70, 70]])

##statistics

In [95]:
a = np.array([5,9,6])

In [96]:
a

array([5, 9, 6])

In [98]:
a.min()

5

In [99]:
a.max()

9

In [100]:
a.sum()

20

In [101]:
a.mean()

6.666666666666667

In [102]:
a.std()    ##standard deviation

1.699673171197595

In [103]:
a.var()   ##variance is the avg.of the squareed deviations from the mean

2.888888888888889

In [104]:
A = np.array([[11,22,33],
             [44,55,66],
             [77,88,99]])

In [105]:
A

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [106]:
A.sum()

495

In [108]:
A.std()

28.401877872187722

In [109]:
A.mean()

55.0

In [110]:
A.var()

806.6666666666666

In [111]:
A.min()

11

In [112]:
A.max()

99

In [113]:
A.sum(axis=0)

array([132, 165, 198])

In [118]:
A.sum(axis=1)

array([ 66, 165, 264])

##Broadcasting and Vectorized operations

In [119]:
A =np.arange(4) 

In [120]:
A

array([0, 1, 2, 3])

In [121]:
A+1

array([1, 2, 3, 4])

In [122]:
A

array([0, 1, 2, 3])

In [123]:
A*2

array([0, 2, 4, 6])

In [124]:
A**3

array([ 0,  1,  8, 27], dtype=int32)

In [125]:
B = np.arange(4)

In [126]:
B

array([0, 1, 2, 3])

In [127]:
A +B

array([0, 2, 4, 6])

In [128]:
A+=11

In [129]:
A

array([11, 12, 13, 14])

In [131]:
l = [1,5,6,7]  ##multipy with 10

In [132]:
[i * 10 for i in l]

[10, 50, 60, 70]

In [134]:
l

[1, 5, 6, 7]

In [135]:
r =[3,6,7]

In [136]:
[i*4 for i in r]

[12, 24, 28]

##Boolean arrays

In [143]:
a = np.arange(5)

In [144]:
a

array([0, 1, 2, 3, 4])

In [145]:
a[0],a[-1]

(0, 4)

In [147]:
a[[0,-1]]

array([0, 4])

In [149]:
A[[True,True,False,False]]

array([11, 12])

In [150]:
A[[True,False,False,True]]

array([11, 14])

In [151]:
A>=2

array([ True,  True,  True,  True])

In [152]:
A=1

In [153]:
A

1

In [154]:
A<-2

False

In [155]:
A<=2

True

In [156]:
A>=3

False

In [158]:
a.mean()

2.0