In [1]:
import numpy as np

## 1 dimensional array1️⃣

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
b = np.array([3,4,5])

In [5]:
b

array([3, 4, 5])

## 2 dimensional array2️⃣

In [8]:
c = np.array([[6,7,8,8,9],[10,11,12,13,14]])

In [9]:
c

array([[ 6,  7,  8,  8,  9],
       [10, 11, 12, 13, 14]])

In [10]:
d = np.array([[2,5,4,7,8,3],[6,4,9,2,7,1]])

In [11]:
d

array([[2, 5, 4, 7, 8, 3],
       [6, 4, 9, 2, 7, 1]])

## 3 dimensional array🔢

In [158]:
e = np.array([[[2,3],[4,5]],[[9,88],[44,55]]])

In [159]:
e

array([[[ 2,  3],
        [ 4,  5]],

       [[ 9, 88],
        [44, 55]]])

In [15]:
f = np.array([[1],[4],[5]])

In [16]:
f

array([[1],
       [4],
       [5]])

## get dimension

In [17]:
a.ndim

1

In [18]:
b.ndim

1

In [19]:
c.ndim

2

In [20]:
d.ndim

2

In [161]:
e.ndim

3

## get shape

In [28]:
a.shape

(3,)

In [29]:
b.shape

(3,)

In [30]:
c.shape

(2, 5)

In [31]:
d.shape

(2, 6)

In [32]:
e.shape

(4, 2)

In [33]:
f.shape

(3, 1)

## get datatype

In [34]:
a.dtype

dtype('int32')

In [35]:
b.dtype

dtype('int32')

In [36]:
c.dtype

dtype('int32')

In [37]:
d.dtype

dtype('int32')

In [38]:
e.dtype

dtype('int32')

In [39]:
f.dtype

dtype('int32')

## get size

In [40]:
a.itemsize

4

In [41]:
d.itemsize

4

In [42]:
c.itemsize

4

In [43]:
d.itemsize

4

In [44]:
e.itemsize

4

## if we change the datatype as int16 the itemsize would change

In [45]:
a = np.array([1,2,3],dtype='int16')

In [46]:
a

array([1, 2, 3], dtype=int16)

In [47]:
a.itemsize

2

In [48]:
c = np.array([[6,7,8,8,9],[10,11,12,13,14]],dtype ='int16')

In [49]:
c

array([[ 6,  7,  8,  8,  9],
       [10, 11, 12, 13, 14]], dtype=int16)

In [50]:
c.itemsize

2

## get size

In [51]:
a.size

3

In [52]:
b.size

3

In [53]:
c.size

10

In [54]:
d.size

12

In [55]:
e.size

8

In [56]:
f.size

3

## get total size

In [57]:
a.size * a.itemsize

6

In [58]:
## it is shows 6 becoz the data type is changed to int 16 previously

In [59]:
b.size*b.itemsize

12

In [60]:
c.size*c.itemsize        ## it is shows 6 becoz the data type is changed to int 16 previously

20

In [61]:
d.size*d.itemsize

48

In [62]:
e.size*e.itemsize

32

In [63]:
f.size*f.itemsize

12

In [64]:
a.nbytes    ##same as total size

6

In [66]:
b.nbytes

12

In [67]:
c.nbytes

20

In [68]:
d.nbytes

48

In [69]:
d.nbytes

48

In [70]:
e.nbytes

32

In [71]:
f.nbytes

12

In [ ]:
## float

In [72]:
g = np.array([[4.0,8.9,7.0],[3.4,6.7,7.7]])

In [73]:
g

array([[4. , 8.9, 7. ],
       [3.4, 6.7, 7.7]])

In [74]:
g.dtype

dtype('float64')

In [75]:
g.size

6

In [76]:
g.itemsize

8

In [77]:
g.size*g.itemsize

48

In [78]:
g.nbytes

48

## changing the elements,rows,columns,etc.

In [79]:
c = np.array([[6,7,8,8,9],[10,11,12,13,14]])

In [80]:
c

array([[ 6,  7,  8,  8,  9],
       [10, 11, 12, 13, 14]])

In [82]:
## get specific element [row,column]
c[1,3]

13

In [84]:
c[0,1]

7

In [85]:
c[1,4]

14

In [88]:
c[1,2]

12

In [89]:
c[1,-2]

13

In [90]:
c[0,-1]

9

## get specific row

In [93]:
c[0,:]

array([6, 7, 8, 8, 9])

In [94]:
c[1,:]

array([10, 11, 12, 13, 14])

## get a column

In [ ]:
c[:,2]     ## [all the rows, 2nd column]

In [97]:
c[:,4]

array([ 9, 14])

In [98]:
c[1:,4]    ##from 1st row show me the 4th column element

array([14])

In [99]:
## start index:end index: stepsize

In [100]:
c[0,1:4:2]

array([7, 8])

In [101]:
c[1,1:4:2]

array([11, 13])

In [102]:
c[0,2:4:1]

array([8, 8])

In [106]:
d = np.array([[2,5,4,7,8,3],[6,10,9,12,17,1]])

In [107]:
d

array([[ 2,  5,  4,  7,  8,  3],
       [ 6, 10,  9, 12, 17,  1]])

In [108]:
d[1,1:6:2]

array([10, 12,  1])

In [110]:
d[0,2:5:3]

array([4])

In [111]:
d[0,1:4:2]   ## zeroth row-it strats from 1st position and ends at 3rd position

array([5, 7])

In [113]:
d[0,1:6:3]   ## zeroth row-it strats from 1st position and ends at 4th position

array([5, 8])

In [114]:
d[0,1:5:2]

array([5, 7])

In [115]:
d[0,1:3:2]

array([5])

In [116]:
d[1,2:6:5]

array([9])

In [119]:
d[1,1:5:2]

array([10, 12])

In [120]:
d[1,-2:-4:-4]

array([17])

In [124]:
d = np.array([[2,5,4,7,8,3],[6,10,9,12,17,1]])

In [125]:
d

array([[ 2,  5,  4,  7,  8,  3],
       [ 6, 10,  9, 12, 17,  1]])

In [126]:
## changing the element
d[1,5]=20  ##from 1st row chnage the 5th element to 20

In [127]:
d

array([[ 2,  5,  4,  7,  8,  3],
       [ 6, 10,  9, 12, 17, 20]])

In [147]:
d = np.array([[2,5,4,7,8,3],[6,10,9,12,17,1]])

In [148]:
d

array([[ 2,  5,  4,  7,  8,  3],
       [ 6, 10,  9, 12, 17,  1]])

In [149]:
d[:,2]=0    ##all rows,in the 2nd columns turns the elements to 0

In [150]:
d

array([[ 2,  5,  0,  7,  8,  3],
       [ 6, 10,  0, 12, 17,  1]])

In [151]:
d[:,2]=[11,22]     ##all rows,in the 2nd columns turns the elements to 11 and 22

In [152]:
d

array([[ 2,  5, 11,  7,  8,  3],
       [ 6, 10, 22, 12, 17,  1]])

In [162]:
e = np.array([[[2,3],[4,5]],[[9,88],[44,55]]])

In [163]:
e

array([[[ 2,  3],
        [ 4,  5]],

       [[ 9, 88],
        [44, 55]]])

In [164]:
e[0,1,1]      ##In 0 array,1st row,1st element

5

In [165]:
e[1,0,0]      ##getting specific element

9

In [ ]:
##replacing elements

In [167]:
e = np.array([[[2,3],[4,5]],[[9,88],[44,55]]])

In [168]:
e

array([[[ 2,  3],
        [ 4,  5]],

       [[ 9, 88],
        [44, 55]]])

In [169]:
e[:,1,:]

array([[ 4,  5],
       [44, 55]])

In [170]:
e[:,1,:] = [[6,6],[0,0]]

In [171]:
e

array([[[ 2,  3],
        [ 6,  6]],

       [[ 9, 88],
        [ 0,  0]]])