## different type of arrays

In [6]:
import numpy as np

In [ ]:
# all 0's matrix

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [10]:
np.zeros((2,3,4,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [14]:
#all is matrix
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [16]:
#changing to other number
np.full((4,2,3),99)     ## 4 matrix,2 rows,3 columns

array([[[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [32]:
#changing to other number using (full_like)
c = np.array([[6,7,8,8,9],[10,11,12,13,14]])

In [24]:
np.full((5,4,5),33)  ##5 matrix,4 rows,5 columns

array([[[33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33]],

       [[33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33]],

       [[33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33]],

       [[33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33]],

       [[33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33],
        [33, 33, 33, 33, 33]]])

In [18]:
c

array([[ 6,  7,  8,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
np.full_like(c,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [25]:
#random decimal numbers
np.random.rand(4,5)

array([[0.83398812, 0.40625673, 0.77079108, 0.29301683, 0.59910077],
       [0.64769621, 0.68819746, 0.70631164, 0.8647158 , 0.76513674],
       [0.37422114, 0.7206774 , 0.85619776, 0.6097913 , 0.03524564],
       [0.25302536, 0.58222774, 0.90146129, 0.16369819, 0.95286251]])

In [26]:
np.random.rand(2,3)

array([[0.22267301, 0.81207533, 0.65613387],
       [0.81872888, 0.93325293, 0.33690697]])

In [27]:
np.random.rand(2,2)

array([[0.18384039, 0.66055743],
       [0.94018035, 0.44671501]])

In [29]:
np.random.random_sample(c.shape)

array([[0.4392788 , 0.88919078, 0.40935269, 0.10544228, 0.4202817 ],
       [0.89635933, 0.78065714, 0.22166495, 0.93112126, 0.56359187]])

In [33]:
np.random.rand(7)

array([0.59207839, 0.60525351, 0.7153797 , 0.32034598, 0.98559032,
       0.04944152, 0.02414101])

In [35]:
np.random.randint(7,size=(2,3))

array([[0, 0, 1],
       [6, 5, 5]])

In [38]:
np.random.randint(7,size=(3,3))

array([[3, 1, 5],
       [2, 3, 3],
       [6, 1, 1]])

In [39]:
np.random.randint(8,size=(3,3))

array([[0, 0, 0],
       [6, 0, 4],
       [2, 1, 3]])

In [41]:
np.random.randint(-2,4,size=(2,3))

array([[-2, -2,  2],
       [ 1, -2, -2]])

In [42]:
## identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [44]:
np.identity(1)

array([[1.]])

In [45]:
np.identity(7)😁

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [46]:
np.identity(0)

array([], shape=(0, 0), dtype=float64)

In [47]:
np.identity(100)😜

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [48]:
##repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [49]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)

In [50]:
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [53]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)

In [54]:
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [55]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)

In [56]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [66]:
#Excercise
p = np.ones((5,5))
p

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
r = np.zeros((3,3))

In [59]:
r

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [60]:
r[1,1]=9

In [61]:
r

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [67]:
p[1:4,1:4]=r

In [68]:
p

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
#exercise
a = np.array([1,2,3])

In [70]:
a

array([1, 2, 3])

In [71]:
b=a

In [72]:
a

array([1, 2, 3])

In [73]:
b

array([1, 2, 3])

In [74]:
b[2]=11

In [75]:
b

array([ 1,  2, 11])

In [76]:
a

array([ 1,  2, 11])

In [79]:
#copy
b=a.copy()

In [80]:
b

array([ 1,  2, 11])

In [81]:
a

array([ 1,  2, 11])